apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  creationTimestamp: "2024-11-29T00:06:20Z"
  name: krew
spec:
  caveats: |
    krew is now installed! To start using kubectl plugins, you need to add
    krew's installation directory to your PATH:

      * macOS/Linux:
        - Add the following to your ~/.bashrc or ~/.zshrc:
            export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
        - Restart your shell.

      * Windows: Add %USERPROFILE%\.krew\bin to your PATH environment variable

    To list krew commands and to get help, run:
      $ kubectl krew
    For a full list of available plugins, run:
      $ kubectl krew search

    You can find documentation at
      https://krew.sigs.k8s.io/docs/user-guide/quickstart/.
  homepage: https://krew.sigs.k8s.io/
  platforms:
  - bin: krew
    files:
    - from: ./krew-darwin_amd64
      to: krew
    - from: ./LICENSE
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: darwin
    sha256: 5f4d2f34868a87cf1188212cf7cb598e76a32f389054089aad1fa46e6daf1e1b
    uri: https://github.com/kubernetes-sigs/krew/releases/download/v0.4.4/krew-darwin_amd64.tar.gz
  - bin: krew
    files:
    - from: ./krew-darwin_arm64
      to: krew
    - from: ./LICENSE
      to: .
    selector:
      matchLabels:
        arch: arm64
        os: darwin
    sha256: e6ac776140b228d6bdfda11247baf4e9b11068f42005d0975fc260c629954464
    uri: https://github.com/kubernetes-sigs/krew/releases/download/v0.4.4/krew-darwin_arm64.tar.gz
  - bin: krew
    files:
    - from: ./krew-linux_amd64
      to: krew
    - from: ./LICENSE
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: linux
    sha256: e471396b0ed4f2be092b4854cc030dfcbb12b86197972e7bef0cb89ad9c72477
    uri: https://github.com/kubernetes-sigs/krew/releases/download/v0.4.4/krew-linux_amd64.tar.gz
  - bin: krew
    files:
    - from: ./krew-linux_arm
      to: krew
    - from: ./LICENSE
      to: .
    selector:
      matchLabels:
        arch: arm
        os: linux
    sha256: 4f3d550227e014f3ba7c72031108ffda0654cb755f70eb96be413a5102d23333
    uri: https://github.com/kubernetes-sigs/krew/releases/download/v0.4.4/krew-linux_arm.tar.gz
  - bin: krew
    files:
    - from: ./krew-linux_arm64
      to: krew
    - from: ./LICENSE
      to: .
    selector:
      matchLabels:
        arch: arm64
        os: linux
    sha256: f8f0cdbf698ed3e8cb46e7bd213754701341a10e11ccb69c90d4863e0cf5a16a
    uri: https://github.com/kubernetes-sigs/krew/releases/download/v0.4.4/krew-linux_arm64.tar.gz
  - bin: krew
    files:
    - from: ./krew-linux_ppc64le
      to: krew
    - from: ./LICENSE
      to: .
    selector:
      matchLabels:
        arch: ppc64le
        os: linux
    sha256: 966ee6d2b113c9ed7d8c6072ae3b24d5041da9a658b6197249634c5c76ba37a9
    uri: https://github.com/kubernetes-sigs/krew/releases/download/v0.4.4/krew-linux_ppc64le.tar.gz
  - bin: krew.exe
    files:
    - from: ./krew-windows_amd64.exe
      to: krew.exe
    - from: ./LICENSE
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: windows
    sha256: da0dfeb2a598f11fb9ce871ee7f3b1a69beb371a45f531ee65a71b2201511d28
    uri: https://github.com/kubernetes-sigs/krew/releases/download/v0.4.4/krew-windows_amd64.tar.gz
  shortDescription: Package manager for kubectl plugins.
  version: v0.4.4
status:
  source:
    name: default
