apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  creationTimestamp: "2024-11-29T00:07:18Z"
  name: ns
spec:
  caveats: |
    If fzf is installed on your machine, you can interactively choose
    between the entries using the arrow keys, or by fuzzy searching
    as you type.
  description: |
    Also known as "kubens", a utility to set your current namespace and switch
    between them.
  homepage: https://github.com/ahmetb/kubectx
  platforms:
  - bin: kubens
    files:
    - from: kubectx-*/kubens
      to: .
    - from: kubectx-*/LICENSE
      to: .
    selector:
      matchExpressions:
      - key: os
        operator: In
        values:
        - darwin
        - linux
    sha256: c94392fba8dfc5c8075161246749ef71c18f45da82759084664eb96027970004
    uri: https://github.com/ahmetb/kubectx/archive/v0.9.5.tar.gz
  shortDescription: Switch between Kubernetes namespaces
  version: v0.9.5
status:
  source:
    name: default
