kind: Pod
apiVersion: v1
metadata:
  name:multipod
spec:
  containers:
  - name: nginx-contianer
    image: nginx:1.14
    ports:
    - containerPort; 80
  - nmae: centos-continer
    image: quay.io/centos/centos:stream9
    command:
    - sleep
    - "86400"

